### ISSUE TITLE
change direction to connect multiple sensors

### ISSUE THREAD

**Issue by brian-02** [adafruit/Adafruit_CircuitPython_MLX90614#11]
How to change the address that comes from the factory to connect multiple devices

**Comment by ladyada** [comment]
we don't have code/support for doing that.

**Comment by brian-02** [comment]
Do not you know where I can or how can I do it?

**Comment by ladyada** [comment]
you'd have to look through the datasheet, if there's a way to do it..then add the code support

**Comment by brian-02** [comment]
in the data sheet it appears that the smbus address is 0xFh, but I do not know how to change it

**Comment by ladyada** [comment]
probably not changable then

**Comment by brian-02** [comment]
but in the data sheet it says that you can connect up to 127 to a single i2c bus, and in arduino you can do it but I do not know how to do it with raspberry

**Comment by ladyada** [comment]
you'll need to see the arduino library on how to do it, then adapt it. we dont have any more information than you do :)

**Comment by brian-02** [comment]
ok thanks for your help
